// <auto-generated />
using System;
using HikingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikingApp.Migrations
{
    [DbContext(typeof(HikingAppDbContext))]
    [Migration("20250619161108_AddLatLongToHike")]
    partial class AddLatLongToHike
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HikingApp.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Moderate"
                        },
                        new
                        {
                            Id = 3,
                            Level = "Challenging"
                        },
                        new
                        {
                            Id = 4,
                            Level = "Hard"
                        });
                });

            modelBuilder.Entity("HikingApp.Models.Hike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasRestrooms")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDogFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGravel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHandicapAccessible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKidFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaved")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Hikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Forest Ln",
                            City = "Nashville",
                            DateCreated = new DateTime(2025, 6, 18, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(6943),
                            Description = "Peaceful loop through tall trees",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Location = "Cedarwood Forest",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Forest Loop",
                            UserProfileId = 3,
                            Zip = "37011"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "456 River Rd",
                            City = "Knoxville",
                            DateCreated = new DateTime(2025, 6, 17, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7039),
                            Description = "Trail running alongside the riverbank.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "East River Park",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "River Edge Trail",
                            UserProfileId = 4,
                            Zip = "37901"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "789 Bluff Dr",
                            City = "Chattanooga",
                            DateCreated = new DateTime(2025, 6, 16, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7045),
                            Description = "Scenic view from the bluff",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Bluff Point Reserve",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Bluff Overlook",
                            UserProfileId = 5,
                            Zip = "37401"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "321 Lakeview Ave",
                            City = "Clarksville",
                            DateCreated = new DateTime(2025, 6, 15, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7048),
                            Description = "Goes all the way around the lake!Lots of ducks!",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Location = "Lake Harmony Trails",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Lakeside Path",
                            UserProfileId = 3,
                            Zip = "37040"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine1 = "654 Ridge Rd",
                            City = "Cookeville",
                            DateCreated = new DateTime(2025, 6, 14, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7052),
                            Description = "Challenging hike with rewarding sunset views.",
                            DifficultyId = 1,
                            Distance = 5.4000000000000004,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Summit Ridge View",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Sunset Ridge",
                            UserProfileId = 4,
                            Zip = "38501"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine1 = "987 Falls Blvd",
                            City = "Sparta",
                            DateCreated = new DateTime(2025, 6, 13, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7061),
                            Description = "steep, rocky trail, not for beginners.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Crystal Falls Preserve",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Waterfall Trail",
                            UserProfileId = 5,
                            Zip = "38583"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine1 = "159 Rock Ln",
                            City = "Tullahoma",
                            DateCreated = new DateTime(2025, 6, 12, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7074),
                            Description = "Lots of rocks and boulders on this trail",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Ironrock Trailhead",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Rocky Path",
                            UserProfileId = 3,
                            Zip = "37388"
                        },
                        new
                        {
                            Id = 8,
                            AddressLine1 = "753 Birdsong Ct",
                            City = "Columbia",
                            DateCreated = new DateTime(2025, 6, 11, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7077),
                            Description = "Great nature watching along the trail, lots of birds.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Springwatch Preserve",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Birdwatch Loop",
                            UserProfileId = 4,
                            Zip = "38401"
                        },
                        new
                        {
                            Id = 9,
                            AddressLine1 = "111 Pine Ln",
                            City = "Jackson",
                            DateCreated = new DateTime(2025, 6, 10, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7080),
                            Description = "short path, great for kids, can be muddy.",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = false,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Pine Hollow Woods",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Pine Hollow",
                            UserProfileId = 5,
                            Zip = "38301"
                        },
                        new
                        {
                            Id = 10,
                            AddressLine1 = "222 Creek Rd",
                            City = "Murfreesboro",
                            DateCreated = new DateTime(2025, 6, 9, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7083),
                            Description = "multiple creek crossings on path, water comes up to knee height.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Creekstone Trail",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Creek Crossing",
                            UserProfileId = 3,
                            Zip = "37130"
                        },
                        new
                        {
                            Id = 11,
                            AddressLine1 = "333 Meadow Pkwy",
                            City = "Brentwood",
                            DateCreated = new DateTime(2025, 6, 8, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7099),
                            Description = "Beautiful views of wild flowers!",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Meadowlark Trail",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Meadow Breeze",
                            UserProfileId = 4,
                            Zip = "37027"
                        },
                        new
                        {
                            Id = 12,
                            AddressLine1 = "444 Valley Ln",
                            City = "Gallatin",
                            DateCreated = new DateTime(2025, 6, 7, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7102),
                            Description = "Steep hills, not very busy early in the morning.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Whispering Valley",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Valley Hike",
                            UserProfileId = 5,
                            Zip = "37066"
                        },
                        new
                        {
                            Id = 13,
                            AddressLine1 = "555 Step Hill Rd",
                            City = "Johnson City",
                            DateCreated = new DateTime(2025, 6, 6, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7106),
                            Description = "Trail has tons of steps!!",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Location = "Canyon Staircase",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Steep Steps",
                            UserProfileId = 3,
                            Zip = "37601"
                        },
                        new
                        {
                            Id = 14,
                            AddressLine1 = "666 Maple St",
                            City = "Lebanon",
                            DateCreated = new DateTime(2025, 6, 5, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7109),
                            Description = "big trees, lots of shade, great for a day hike!",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Maple Shade Woods",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Maple Grove",
                            UserProfileId = 4,
                            Zip = "37087"
                        },
                        new
                        {
                            Id = 15,
                            AddressLine1 = "777 Hilltop Dr",
                            City = "Dickson",
                            DateCreated = new DateTime(2025, 6, 4, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7112),
                            Description = "Open climb with big views",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Hilltop Ascent",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Big Hill",
                            UserProfileId = 5,
                            Zip = "37055"
                        },
                        new
                        {
                            Id = 16,
                            AddressLine1 = "888 Shady Trl",
                            City = "McMinnville",
                            DateCreated = new DateTime(2025, 6, 3, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7131),
                            Description = "Cooling shade and shallow water.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = false,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Shady Glen Trail",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Shady Creek",
                            UserProfileId = 3,
                            Zip = "37110"
                        },
                        new
                        {
                            Id = 17,
                            AddressLine1 = "999 Heritage Way",
                            City = "Franklin",
                            DateCreated = new DateTime(2025, 6, 2, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7135),
                            Description = "Passes Civil War Sites",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Location = "Civil Ridge Trail",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Historic Trail",
                            UserProfileId = 4,
                            Zip = "37064"
                        },
                        new
                        {
                            Id = 18,
                            AddressLine1 = "1010 Dawn Dr",
                            City = "Oak Ridge",
                            DateCreated = new DateTime(2025, 6, 1, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7139),
                            Description = "Best at dawn, steep but short.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Sunrise Bluff Trail",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Sunrise Summit",
                            UserProfileId = 5,
                            Zip = "37830"
                        },
                        new
                        {
                            Id = 19,
                            AddressLine1 = "1111 Nature Ln",
                            City = "Smyrna",
                            DateCreated = new DateTime(2025, 5, 31, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7142),
                            Description = "Educational signs along the way.",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Nature Education Loop",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Nature Walk",
                            UserProfileId = 3,
                            Zip = "37167"
                        },
                        new
                        {
                            Id = 20,
                            AddressLine1 = "1212 Ridgecrest Rd",
                            City = "Spring Hill",
                            DateCreated = new DateTime(2025, 5, 30, 11, 11, 7, 920, DateTimeKind.Local).AddTicks(7145),
                            Description = "Breezy and open, moderate challenge",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Location = "Windcrest Hills",
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Windy Ridge",
                            UserProfileId = 4,
                            Zip = "37174"
                        });
                });

            modelBuilder.Entity("HikingApp.Models.HikeLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HikeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HikeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("HikeLikes");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hiking.com",
                            FirstName = "Admin",
                            IdentityUserId = "1a111111-1111-1111-1111-111111111111",
                            ImageLocation = "https://i.pravatar.cc/150?img=47",
                            LastName = "Hiker"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@hiking.com",
                            FirstName = "Standard",
                            IdentityUserId = "2b222222-2222-2222-2222-222222222222",
                            ImageLocation = "https://i.pravatar.cc/150?img=12",
                            LastName = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sarah@email.com",
                            FirstName = "Sarah",
                            IdentityUserId = "3c333333-3333-3333-3333-333333333333",
                            ImageLocation = "https://i.pravatar.cc/150?img=32",
                            LastName = "Woods"
                        },
                        new
                        {
                            Id = 4,
                            Email = "josh@email.com",
                            FirstName = "Josh",
                            IdentityUserId = "4d444444-4444-4444-4444-444444444444",
                            ImageLocation = "https://i.pravatar.cc/150?img=26",
                            LastName = "Trail"
                        },
                        new
                        {
                            Id = 5,
                            Email = "amber@email.com",
                            FirstName = "Amber",
                            IdentityUserId = "5e555555-5555-5555-5555-555555555555",
                            ImageLocation = "https://i.pravatar.cc/150?img=45",
                            LastName = "Creek"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-0001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6dab64f4-0aa6-4bb8-900b-b1dc7c160e74",
                            Email = "admin@hiking.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HIKING.COM",
                            NormalizedUserName = "ADMIN@HIKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJEW5lvsTVReMIasVg6PMxDYL+f0AJG0I+h3s/AgoIhfIpYLKlNIK42B4IckMk9p/w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a967aeb8-2689-49ae-81a5-aae581ad3643",
                            TwoFactorEnabled = false,
                            UserName = "admin@hiking.com"
                        },
                        new
                        {
                            Id = "2b222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f5fdf72-5355-42b1-bd3f-fc8f7ea3291a",
                            Email = "user@hiking.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@HIKING.COM",
                            NormalizedUserName = "USER@HIKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGuBvLVrrLXoLSLA/2Eqq1zrTevEFvJV/qHWX7VTyz+IeIXV3lTXraBLC+RwAM5yWw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a2ad783-742b-44ec-a4a7-619194f21622",
                            TwoFactorEnabled = false,
                            UserName = "user@hiking.com"
                        },
                        new
                        {
                            Id = "3c333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ccb281c-e1aa-40b2-88d6-c3812c9c7c42",
                            Email = "sarah@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH@EMAIL.COM",
                            NormalizedUserName = "SARAH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIereXS848ua8bldKixWVc3JgR7RzspqE/Z4xpxZZT/OJ3rzeAOHjxhViDptfrCqSQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb528f48-93d5-4c63-90ea-3f1203fdd27d",
                            TwoFactorEnabled = false,
                            UserName = "sarah@email.com"
                        },
                        new
                        {
                            Id = "4d444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e97e1433-9fff-403f-861d-bc226521be98",
                            Email = "josh@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOSH@EMAIL.COM",
                            NormalizedUserName = "JOSH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIDnkXU5HQ19w9TSH2QMofWiX9lp9dyQsrbK8TceGv7T5S6VdNH6GPCSQE/TJ2HL6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b901b8f0-54b2-4f27-9a78-7b3dc58a9c58",
                            TwoFactorEnabled = false,
                            UserName = "josh@email.com"
                        },
                        new
                        {
                            Id = "5e555555-5555-5555-5555-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c9acaf2-c548-4d40-b894-40d0db4fbaa6",
                            Email = "amber@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "AMBER@EMAIL.COM",
                            NormalizedUserName = "AMBER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJo8W2gORj1nClY4ZDgoz+Q/MTlQvK9Cfw7uBqY4Q5fNDLDVsZ5SSbTaLCH+U9urZw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "12f857cd-1efa-42f4-8919-c246f1ab9210",
                            TwoFactorEnabled = false,
                            UserName = "amber@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1a111111-1111-1111-1111-111111111111",
                            RoleId = "role-admin-0001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HikingApp.Models.Hike", b =>
                {
                    b.HasOne("HikingApp.Models.Difficulty", "Difficulty")
                        .WithMany("Hikes")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp.Models.UserProfile", "UserProfile")
                        .WithMany("Hikes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HikingApp.Models.HikeLike", b =>
                {
                    b.HasOne("HikingApp.Models.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hike");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HikingApp.Models.Difficulty", b =>
                {
                    b.Navigation("Hikes");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.Navigation("Hikes");
                });
#pragma warning restore 612, 618
        }
    }
}
