// <auto-generated />
using System;
using HikingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikingApp.Migrations
{
    [DbContext(typeof(HikingAppDbContext))]
    [Migration("20250701170942_AddFavorite")]
    partial class AddFavorite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateFavorited")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HikeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HikeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("HikingApp.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Moderate"
                        },
                        new
                        {
                            Id = 3,
                            Level = "Challenging"
                        },
                        new
                        {
                            Id = 4,
                            Level = "Hard"
                        });
                });

            modelBuilder.Entity("HikingApp.Models.Hike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasRestrooms")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDogFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGravel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHandicapAccessible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKidFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaved")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Hikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Forest Ln",
                            City = "Nashville",
                            DateCreated = new DateTime(2025, 6, 30, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(8868),
                            Description = "Peaceful loop through tall trees",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Forest Loop",
                            UserProfileId = 3,
                            Zip = "37011"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "456 River Rd",
                            City = "Knoxville",
                            DateCreated = new DateTime(2025, 6, 29, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(8995),
                            Description = "Trail running alongside the riverbank.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "River Edge Trail",
                            UserProfileId = 4,
                            Zip = "37901"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "789 Bluff Dr",
                            City = "Chattanooga",
                            DateCreated = new DateTime(2025, 6, 28, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9000),
                            Description = "Scenic view from the bluff",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Bluff Overlook",
                            UserProfileId = 5,
                            Zip = "37401"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "321 Lakeview Ave",
                            City = "Clarksville",
                            DateCreated = new DateTime(2025, 6, 27, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9003),
                            Description = "Goes all the way around the lake!Lots of ducks!",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Lakeside Path",
                            UserProfileId = 3,
                            Zip = "37040"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine1 = "654 Ridge Rd",
                            City = "Cookeville",
                            DateCreated = new DateTime(2025, 6, 26, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9006),
                            Description = "Challenging hike with rewarding sunset views.",
                            DifficultyId = 1,
                            Distance = 5.4000000000000004,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Sunset Ridge",
                            UserProfileId = 4,
                            Zip = "38501"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine1 = "987 Falls Blvd",
                            City = "Sparta",
                            DateCreated = new DateTime(2025, 6, 25, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9016),
                            Description = "steep, rocky trail, not for beginners.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Waterfall Trail",
                            UserProfileId = 5,
                            Zip = "38583"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine1 = "159 Rock Ln",
                            City = "Tullahoma",
                            DateCreated = new DateTime(2025, 6, 24, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9027),
                            Description = "Lots of rocks and boulders on this trail",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Rocky Path",
                            UserProfileId = 3,
                            Zip = "37388"
                        },
                        new
                        {
                            Id = 8,
                            AddressLine1 = "753 Birdsong Ct",
                            City = "Columbia",
                            DateCreated = new DateTime(2025, 6, 23, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9030),
                            Description = "Great nature watching along the trail, lots of birds.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Birdwatch Loop",
                            UserProfileId = 4,
                            Zip = "38401"
                        },
                        new
                        {
                            Id = 9,
                            AddressLine1 = "111 Pine Ln",
                            City = "Jackson",
                            DateCreated = new DateTime(2025, 6, 22, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9033),
                            Description = "short path, great for kids, can be muddy.",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = false,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Pine Hollow",
                            UserProfileId = 5,
                            Zip = "38301"
                        },
                        new
                        {
                            Id = 10,
                            AddressLine1 = "222 Creek Rd",
                            City = "Murfreesboro",
                            DateCreated = new DateTime(2025, 6, 21, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9036),
                            Description = "multiple creek crossings on path, water comes up to knee height.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Creek Crossing",
                            UserProfileId = 3,
                            Zip = "37130"
                        },
                        new
                        {
                            Id = 11,
                            AddressLine1 = "333 Meadow Pkwy",
                            City = "Brentwood",
                            DateCreated = new DateTime(2025, 6, 20, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9051),
                            Description = "Beautiful views of wild flowers!",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Meadow Breeze",
                            UserProfileId = 4,
                            Zip = "37027"
                        },
                        new
                        {
                            Id = 12,
                            AddressLine1 = "444 Valley Ln",
                            City = "Gallatin",
                            DateCreated = new DateTime(2025, 6, 19, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9054),
                            Description = "Steep hills, not very busy early in the morning.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Valley Hike",
                            UserProfileId = 5,
                            Zip = "37066"
                        },
                        new
                        {
                            Id = 13,
                            AddressLine1 = "555 Step Hill Rd",
                            City = "Johnson City",
                            DateCreated = new DateTime(2025, 6, 18, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9057),
                            Description = "Trail has tons of steps!!",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Steep Steps",
                            UserProfileId = 3,
                            Zip = "37601"
                        },
                        new
                        {
                            Id = 14,
                            AddressLine1 = "666 Maple St",
                            City = "Lebanon",
                            DateCreated = new DateTime(2025, 6, 17, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9060),
                            Description = "big trees, lots of shade, great for a day hike!",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Maple Grove",
                            UserProfileId = 4,
                            Zip = "37087"
                        },
                        new
                        {
                            Id = 15,
                            AddressLine1 = "777 Hilltop Dr",
                            City = "Dickson",
                            DateCreated = new DateTime(2025, 6, 16, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9063),
                            Description = "Open climb with big views",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Big Hill",
                            UserProfileId = 5,
                            Zip = "37055"
                        },
                        new
                        {
                            Id = 16,
                            AddressLine1 = "888 Shady Trl",
                            City = "McMinnville",
                            DateCreated = new DateTime(2025, 6, 15, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9081),
                            Description = "Cooling shade and shallow water.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = false,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Shady Creek",
                            UserProfileId = 3,
                            Zip = "37110"
                        },
                        new
                        {
                            Id = 17,
                            AddressLine1 = "999 Heritage Way",
                            City = "Franklin",
                            DateCreated = new DateTime(2025, 6, 14, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9084),
                            Description = "Passes Civil War Sites",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Historic Trail",
                            UserProfileId = 4,
                            Zip = "37064"
                        },
                        new
                        {
                            Id = 18,
                            AddressLine1 = "1010 Dawn Dr",
                            City = "Oak Ridge",
                            DateCreated = new DateTime(2025, 6, 13, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9087),
                            Description = "Best at dawn, steep but short.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Sunrise Summit",
                            UserProfileId = 5,
                            Zip = "37830"
                        },
                        new
                        {
                            Id = 19,
                            AddressLine1 = "1111 Nature Ln",
                            City = "Smyrna",
                            DateCreated = new DateTime(2025, 6, 12, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9091),
                            Description = "Educational signs along the way.",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Nature Walk",
                            UserProfileId = 3,
                            Zip = "37167"
                        },
                        new
                        {
                            Id = 20,
                            AddressLine1 = "1212 Ridgecrest Rd",
                            City = "Spring Hill",
                            DateCreated = new DateTime(2025, 6, 11, 12, 9, 42, 440, DateTimeKind.Local).AddTicks(9094),
                            Description = "Breezy and open, moderate challenge",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Latitude = 0.0,
                            Longitude = 0.0,
                            State = "TN",
                            Title = "Windy Ridge",
                            UserProfileId = 4,
                            Zip = "37174"
                        });
                });

            modelBuilder.Entity("HikingApp.Models.HikeLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HikeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HikeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("HikeLikes");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hiking.com",
                            FirstName = "Admin",
                            IdentityUserId = "1a111111-1111-1111-1111-111111111111",
                            ImageLocation = "https://i.pravatar.cc/150?img=47",
                            LastName = "Hiker"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@hiking.com",
                            FirstName = "Standard",
                            IdentityUserId = "2b222222-2222-2222-2222-222222222222",
                            ImageLocation = "https://i.pravatar.cc/150?img=12",
                            LastName = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sarah@email.com",
                            FirstName = "Sarah",
                            IdentityUserId = "3c333333-3333-3333-3333-333333333333",
                            ImageLocation = "https://i.pravatar.cc/150?img=32",
                            LastName = "Woods"
                        },
                        new
                        {
                            Id = 4,
                            Email = "josh@email.com",
                            FirstName = "Josh",
                            IdentityUserId = "4d444444-4444-4444-4444-444444444444",
                            ImageLocation = "https://i.pravatar.cc/150?img=26",
                            LastName = "Trail"
                        },
                        new
                        {
                            Id = 5,
                            Email = "amber@email.com",
                            FirstName = "Amber",
                            IdentityUserId = "5e555555-5555-5555-5555-555555555555",
                            ImageLocation = "https://i.pravatar.cc/150?img=45",
                            LastName = "Creek"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-0001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9981eceb-4101-44e0-8aff-a05fab2c9154",
                            Email = "admin@hiking.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HIKING.COM",
                            NormalizedUserName = "ADMIN@HIKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPpTT//5mYTA2tVc4kV9mXK0TzT4phApBjqhfjJfN/Yy4UACQzDy25+t6iTvM08ctg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f47f10f7-1a23-4f63-88f3-c430255ad7b4",
                            TwoFactorEnabled = false,
                            UserName = "admin@hiking.com"
                        },
                        new
                        {
                            Id = "2b222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4a8e3438-d7a2-438f-8a23-48c10e52d092",
                            Email = "user@hiking.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@HIKING.COM",
                            NormalizedUserName = "USER@HIKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOnD0Bzyh0Oly90pZHGFYJ+hw0cGiNbQ7sJFNVoGnC57hJwcP4wTFP6ynlLlDckyVA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b937d90f-f3df-4134-ad12-c5c407013267",
                            TwoFactorEnabled = false,
                            UserName = "user@hiking.com"
                        },
                        new
                        {
                            Id = "3c333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "51eff849-cce3-433f-a53d-790f34c61f83",
                            Email = "sarah@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH@EMAIL.COM",
                            NormalizedUserName = "SARAH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOpTDQFVBnGdkRkuRj1MABv/YOyPXCvFOAZ34Lg/BboMdBYHK9Olj3MqAp49j5OxHg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56d38c61-a656-4b29-806f-9d1a1e3f8972",
                            TwoFactorEnabled = false,
                            UserName = "sarah@email.com"
                        },
                        new
                        {
                            Id = "4d444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f87fb24e-2a29-45df-93c6-00b5bc081d14",
                            Email = "josh@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOSH@EMAIL.COM",
                            NormalizedUserName = "JOSH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMuCof9nvNfw019n06hey9MDlFp14E3fUmmwU/HlJeCjaG6pR+vretcvrSDTAsrwUA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "15e3c3b2-48c7-4a7b-9389-60b97005609d",
                            TwoFactorEnabled = false,
                            UserName = "josh@email.com"
                        },
                        new
                        {
                            Id = "5e555555-5555-5555-5555-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "183fca14-a235-42f0-9636-380f221740f7",
                            Email = "amber@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "AMBER@EMAIL.COM",
                            NormalizedUserName = "AMBER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEONcvK2UenML2FEuYGSdbpx1lHtvXJLWTNUmQbAcsOHP0cFJ61jFrKwUWVHZnr55jA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c08fa234-14f8-4d64-89cd-6723959cedad",
                            TwoFactorEnabled = false,
                            UserName = "amber@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1a111111-1111-1111-1111-111111111111",
                            RoleId = "role-admin-0001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Favorite", b =>
                {
                    b.HasOne("HikingApp.Models.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hike");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HikingApp.Models.Hike", b =>
                {
                    b.HasOne("HikingApp.Models.Difficulty", "Difficulty")
                        .WithMany("Hikes")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp.Models.UserProfile", "UserProfile")
                        .WithMany("Hikes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HikingApp.Models.HikeLike", b =>
                {
                    b.HasOne("HikingApp.Models.Hike", "Hike")
                        .WithMany()
                        .HasForeignKey("HikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hike");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HikingApp.Models.Difficulty", b =>
                {
                    b.Navigation("Hikes");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.Navigation("Hikes");
                });
#pragma warning restore 612, 618
        }
    }
}
