// <auto-generated />
using System;
using HikingApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HikingApp.Migrations
{
    [DbContext(typeof(HikingAppDbContext))]
    [Migration("20250616161831_SeedHikesWithAddress")]
    partial class SeedHikesWithAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HikingApp.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = "Easy"
                        },
                        new
                        {
                            Id = 2,
                            Level = "Moderate"
                        },
                        new
                        {
                            Id = 3,
                            Level = "Challenging"
                        },
                        new
                        {
                            Id = 4,
                            Level = "Hard"
                        });
                });

            modelBuilder.Entity("HikingApp.Models.Hike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("integer");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasRestrooms")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDogFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGravel")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHandicapAccessible")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKidFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaved")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Hikes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "123 Forest Ln",
                            City = "Nashville",
                            DateCreated = new DateTime(2025, 6, 15, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1067),
                            Description = "Peaceful loop through tall trees",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Location = "Cedarwood Forest",
                            State = "TN",
                            Title = "Forest Loop",
                            UserProfileId = 3,
                            Zip = "37011"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "456 River Rd",
                            City = "Knoxville",
                            DateCreated = new DateTime(2025, 6, 14, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1159),
                            Description = "Trail running alongside the riverbank.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "East River Park",
                            State = "TN",
                            Title = "River Edge Trail",
                            UserProfileId = 4,
                            Zip = "37901"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine1 = "789 Bluff Dr",
                            City = "Chattanooga",
                            DateCreated = new DateTime(2025, 6, 13, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1164),
                            Description = "Scenic view from the bluff",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Bluff Point Reserve",
                            State = "TN",
                            Title = "Bluff Overlook",
                            UserProfileId = 5,
                            Zip = "37401"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine1 = "321 Lakeview Ave",
                            City = "Clarksville",
                            DateCreated = new DateTime(2025, 6, 12, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1168),
                            Description = "Goes all the way around the lake!Lots of ducks!",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Location = "Lake Harmony Trails",
                            State = "TN",
                            Title = "Lakeside Path",
                            UserProfileId = 3,
                            Zip = "37040"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine1 = "654 Ridge Rd",
                            City = "Cookeville",
                            DateCreated = new DateTime(2025, 6, 11, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1172),
                            Description = "Challenging hike with rewarding sunset views.",
                            DifficultyId = 1,
                            Distance = 5.4000000000000004,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Summit Ridge View",
                            State = "TN",
                            Title = "Sunset Ridge",
                            UserProfileId = 4,
                            Zip = "38501"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine1 = "987 Falls Blvd",
                            City = "Sparta",
                            DateCreated = new DateTime(2025, 6, 10, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1183),
                            Description = "steep, rocky trail, not for beginners.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Crystal Falls Preserve",
                            State = "TN",
                            Title = "Waterfall Trail",
                            UserProfileId = 5,
                            Zip = "38583"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine1 = "159 Rock Ln",
                            City = "Tullahoma",
                            DateCreated = new DateTime(2025, 6, 9, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1195),
                            Description = "Lots of rocks and boulders on this trail",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Location = "Ironrock Trailhead",
                            State = "TN",
                            Title = "Rocky Path",
                            UserProfileId = 3,
                            Zip = "37388"
                        },
                        new
                        {
                            Id = 8,
                            AddressLine1 = "753 Birdsong Ct",
                            City = "Columbia",
                            DateCreated = new DateTime(2025, 6, 8, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1199),
                            Description = "Great nature watching along the trail, lots of birds.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Springwatch Preserve",
                            State = "TN",
                            Title = "Birdwatch Loop",
                            UserProfileId = 4,
                            Zip = "38401"
                        },
                        new
                        {
                            Id = 9,
                            AddressLine1 = "111 Pine Ln",
                            City = "Jackson",
                            DateCreated = new DateTime(2025, 6, 7, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1203),
                            Description = "short path, great for kids, can be muddy.",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = false,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Pine Hollow Woods",
                            State = "TN",
                            Title = "Pine Hollow",
                            UserProfileId = 5,
                            Zip = "38301"
                        },
                        new
                        {
                            Id = 10,
                            AddressLine1 = "222 Creek Rd",
                            City = "Murfreesboro",
                            DateCreated = new DateTime(2025, 6, 6, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1206),
                            Description = "multiple creek crossings on path, water comes up to knee height.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Location = "Creekstone Trail",
                            State = "TN",
                            Title = "Creek Crossing",
                            UserProfileId = 3,
                            Zip = "37130"
                        },
                        new
                        {
                            Id = 11,
                            AddressLine1 = "333 Meadow Pkwy",
                            City = "Brentwood",
                            DateCreated = new DateTime(2025, 6, 5, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1225),
                            Description = "Beautiful views of wild flowers!",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Meadowlark Trail",
                            State = "TN",
                            Title = "Meadow Breeze",
                            UserProfileId = 4,
                            Zip = "37027"
                        },
                        new
                        {
                            Id = 12,
                            AddressLine1 = "444 Valley Ln",
                            City = "Gallatin",
                            DateCreated = new DateTime(2025, 6, 4, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1229),
                            Description = "Steep hills, not very busy early in the morning.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Whispering Valley",
                            State = "TN",
                            Title = "Valley Hike",
                            UserProfileId = 5,
                            Zip = "37066"
                        },
                        new
                        {
                            Id = 13,
                            AddressLine1 = "555 Step Hill Rd",
                            City = "Johnson City",
                            DateCreated = new DateTime(2025, 6, 3, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1232),
                            Description = "Trail has tons of steps!!",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Location = "Canyon Staircase",
                            State = "TN",
                            Title = "Steep Steps",
                            UserProfileId = 3,
                            Zip = "37601"
                        },
                        new
                        {
                            Id = 14,
                            AddressLine1 = "666 Maple St",
                            City = "Lebanon",
                            DateCreated = new DateTime(2025, 6, 2, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1274),
                            Description = "big trees, lots of shade, great for a day hike!",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Maple Shade Woods",
                            State = "TN",
                            Title = "Maple Grove",
                            UserProfileId = 4,
                            Zip = "37087"
                        },
                        new
                        {
                            Id = 15,
                            AddressLine1 = "777 Hilltop Dr",
                            City = "Dickson",
                            DateCreated = new DateTime(2025, 6, 1, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1278),
                            Description = "Open climb with big views",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = false,
                            IsPaved = false,
                            Location = "Hilltop Ascent",
                            State = "TN",
                            Title = "Big Hill",
                            UserProfileId = 5,
                            Zip = "37055"
                        },
                        new
                        {
                            Id = 16,
                            AddressLine1 = "888 Shady Trl",
                            City = "McMinnville",
                            DateCreated = new DateTime(2025, 5, 31, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1293),
                            Description = "Cooling shade and shallow water.",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = false,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Shady Glen Trail",
                            State = "TN",
                            Title = "Shady Creek",
                            UserProfileId = 3,
                            Zip = "37110"
                        },
                        new
                        {
                            Id = 17,
                            AddressLine1 = "999 Heritage Way",
                            City = "Franklin",
                            DateCreated = new DateTime(2025, 5, 30, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1299),
                            Description = "Passes Civil War Sites",
                            DifficultyId = 1,
                            Distance = 1.8,
                            HasRestrooms = false,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = true,
                            IsKidFriendly = false,
                            IsPaved = true,
                            Location = "Civil Ridge Trail",
                            State = "TN",
                            Title = "Historic Trail",
                            UserProfileId = 4,
                            Zip = "37064"
                        },
                        new
                        {
                            Id = 18,
                            AddressLine1 = "1010 Dawn Dr",
                            City = "Oak Ridge",
                            DateCreated = new DateTime(2025, 5, 29, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1303),
                            Description = "Best at dawn, steep but short.",
                            DifficultyId = 2,
                            Distance = 2.7000000000000002,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Sunrise Bluff Trail",
                            State = "TN",
                            Title = "Sunrise Summit",
                            UserProfileId = 5,
                            Zip = "37830"
                        },
                        new
                        {
                            Id = 19,
                            AddressLine1 = "1111 Nature Ln",
                            City = "Smyrna",
                            DateCreated = new DateTime(2025, 5, 28, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1307),
                            Description = "Educational signs along the way.",
                            DifficultyId = 3,
                            Distance = 3.6000000000000001,
                            HasRestrooms = true,
                            IsDogFriendly = true,
                            IsGravel = false,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Nature Education Loop",
                            State = "TN",
                            Title = "Nature Walk",
                            UserProfileId = 3,
                            Zip = "37167"
                        },
                        new
                        {
                            Id = 20,
                            AddressLine1 = "1212 Ridgecrest Rd",
                            City = "Spring Hill",
                            DateCreated = new DateTime(2025, 5, 27, 11, 18, 31, 137, DateTimeKind.Local).AddTicks(1310),
                            Description = "Breezy and open, moderate challenge",
                            DifficultyId = 4,
                            Distance = 4.5,
                            HasRestrooms = true,
                            IsDogFriendly = false,
                            IsGravel = true,
                            IsHandicapAccessible = false,
                            IsKidFriendly = true,
                            IsPaved = false,
                            Location = "Windcrest Hills",
                            State = "TN",
                            Title = "Windy Ridge",
                            UserProfileId = 4,
                            Zip = "37174"
                        });
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageLocation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hiking.com",
                            FirstName = "Admin",
                            IdentityUserId = "1a111111-1111-1111-1111-111111111111",
                            ImageLocation = "https://i.pravatar.cc/150?img=47",
                            LastName = "Hiker"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@hiking.com",
                            FirstName = "Standard",
                            IdentityUserId = "2b222222-2222-2222-2222-222222222222",
                            ImageLocation = "https://i.pravatar.cc/150?img=12",
                            LastName = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sarah@email.com",
                            FirstName = "Sarah",
                            IdentityUserId = "3c333333-3333-3333-3333-333333333333",
                            ImageLocation = "https://i.pravatar.cc/150?img=32",
                            LastName = "Woods"
                        },
                        new
                        {
                            Id = 4,
                            Email = "josh@email.com",
                            FirstName = "Josh",
                            IdentityUserId = "4d444444-4444-4444-4444-444444444444",
                            ImageLocation = "https://i.pravatar.cc/150?img=26",
                            LastName = "Trail"
                        },
                        new
                        {
                            Id = 5,
                            Email = "amber@email.com",
                            FirstName = "Amber",
                            IdentityUserId = "5e555555-5555-5555-5555-555555555555",
                            ImageLocation = "https://i.pravatar.cc/150?img=45",
                            LastName = "Creek"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "role-admin-0001",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a111111-1111-1111-1111-111111111111",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ab563685-2111-454b-88eb-89614613e04a",
                            Email = "admin@hiking.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@HIKING.COM",
                            NormalizedUserName = "ADMIN@HIKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAECUyXwN3OSNKMGnJ8W2dlOXin7xfjXYHs3rFHWkVeVZDuN1gBlq2WcZmBem6VRsVIA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "448e6e7c-d786-4178-a9ef-080be9356a03",
                            TwoFactorEnabled = false,
                            UserName = "admin@hiking.com"
                        },
                        new
                        {
                            Id = "2b222222-2222-2222-2222-222222222222",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6faf4e36-83aa-486f-add7-256f87e68721",
                            Email = "user@hiking.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@HIKING.COM",
                            NormalizedUserName = "USER@HIKING.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENCZ7ERnBn3R+sRFLVCaEN/Fk1+un6BWnJV+zfCc2Te90Ed+mv/fAcq1pW3f9BNRhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "926eaf5c-2ca1-4f63-8204-3e20685c3829",
                            TwoFactorEnabled = false,
                            UserName = "user@hiking.com"
                        },
                        new
                        {
                            Id = "3c333333-3333-3333-3333-333333333333",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fdec6be8-a5e4-4ec9-a8bf-2858788a5617",
                            Email = "sarah@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARAH@EMAIL.COM",
                            NormalizedUserName = "SARAH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENeUgmdb6tbBATo5kqhsCglXBjOgv8DYHGgHRxekGMERNhPrJIXKfaCkCEpJ3sdVfg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f51cd4a7-9102-4efe-a634-b954b6a2fe2c",
                            TwoFactorEnabled = false,
                            UserName = "sarah@email.com"
                        },
                        new
                        {
                            Id = "4d444444-4444-4444-4444-444444444444",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c5d9f21-4287-478b-b634-8ed367fc78c5",
                            Email = "josh@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOSH@EMAIL.COM",
                            NormalizedUserName = "JOSH@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEONWwFSWUC8snA1XHo6zspTOhW4VQos828tG1AKGw7IUNHXUa5QLU8ipaG8nOQnrcw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8a321213-ca70-4b87-9558-5a742440bad9",
                            TwoFactorEnabled = false,
                            UserName = "josh@email.com"
                        },
                        new
                        {
                            Id = "5e555555-5555-5555-5555-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "da68d73d-4090-41c2-8dc0-180987f90967",
                            Email = "amber@email.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "AMBER@EMAIL.COM",
                            NormalizedUserName = "AMBER@EMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPpJ/KEzQvfM3GSt96WgkBeAO0dVpxHgTlbUcTHcapJKKRvI5Y/7jYxAqbrCE9LyRw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "57ee9374-36eb-4fe5-a593-b2951a3723ec",
                            TwoFactorEnabled = false,
                            UserName = "amber@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1a111111-1111-1111-1111-111111111111",
                            RoleId = "role-admin-0001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HikingApp.Models.Hike", b =>
                {
                    b.HasOne("HikingApp.Models.Difficulty", "Difficulty")
                        .WithMany("Hikes")
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HikingApp.Models.UserProfile", "UserProfile")
                        .WithMany("Hikes")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HikingApp.Models.Difficulty", b =>
                {
                    b.Navigation("Hikes");
                });

            modelBuilder.Entity("HikingApp.Models.UserProfile", b =>
                {
                    b.Navigation("Hikes");
                });
#pragma warning restore 612, 618
        }
    }
}
